// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

export type AutoReviewStartResponse = { turn: Turn, 
/**
 * Identifies the thread where auto-review runs.
 *
 * For inline runs, this is the original thread id.
 * For detached runs, this is the id of the new review thread.
 */
reviewThreadId: string, };
